
meta_data:
  pipeline_exp_name: "benchmark"
  description: "the complete training pipeline"
  num_workers: 1
  use_gpu: true
  key_config:
    common:
      model: "model"
      dataset: "data"
      img_size: "img_size"
    algo_training:
      lr: "lr"
      batch_size: "bs"
      alpha: "alpha"
      dropout: "drop"

common:
  model: VAE_conv
  dataset: MNIST
  img_size: 32

algo_training:
  variables:
    lr: [0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1]  
    epoches: [20]
    batch_size: [64, 128, 256]
    latent_dim: [1]
    alpha: [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10]
    dropout: [0.1, 0.2, 0.3]
    seed: [111]
    arch: [conv]

  constants:
    exp_name: "vae_train"  # exp_name is required
    script_path: exp_script.py
    optimizer: adam
    loss: mse
