
meta_data:
  pipeline_exp_name: "benchmark"
  description: "the complete training pipeline"
  num_workers: 1
  use_gpu: true
  key_config:
    common:
      model: "model"
      dataset: "data"
      img_size: "img_size"
    algo_training:
      alpha: "alpha"
      latent_dim: "dim"

common:
  model: VAE 
  dataset: MNIST
  img_size: 32

algo_training:
  variables:
    lr: [0.002] 
    epoches: [20]
    batch_size: [64]
    latent_dim: [1]
    alpha: [0.000008]
    step: [1]
    arch: [mlp]

  constants:
    exp_name: "vae_train"  # exp_name is required
    script_path: exp_script.py
    seed: 111
